### ISSUE TITLE
Bug: Map Icon on Interest page color is wrong

### ISSUE THREAD

**Issue by nickfranciosi** [lonelyplanet/backpack-ui#202]
Steps to reproduce:

- Go to http://www.lonelyplanet.com/wildlife-and-nature/
- Scroll down to "Destinations" section
![screen shot 2017-04-07 at 9 30 44 am](https://cloud.githubusercontent.com/assets/4378776/24804701/f2e5e294-1b74-11e7-88ac-1283c429b925.png)

- Icon svg has fill `#fff` needs to be the proper red color for sights

**Comment by ruebel** [comment]
Good call Nick! That really needs fixin'.
