### ISSUE TITLE
Refactor existing tabbed nav (backpack) to fit public profile needs

### ISSUE THREAD

**Issue by nickfranciosi** [lonelyplanet/backpack-ui#218]
update existing ui for tabbed nav to be compatible with the needs for the public profile page
https://github.com/lonelyplanet/backpack-ui/tree/master/src/components/tabbedNav

- [ ] When a navigation item is clicked the content underneath should swap out
- [ ] When a navigation item is clicked the active bar should move to that new item
- [ ] Navigation items should be left aligned 

_double check with ux about how they were envisioning this would work to make sure we cover all bases_

<img width="695" alt="screen shot 2017-04-12 at 3 55 26 pm" src="https://cloud.githubusercontent.com/assets/4378776/24979065/8210bcb0-1f98-11e7-87c6-ba55f985b7be.png">

**Comment by thomasthesecond** [comment]
Backpack has a component named SectionalNav which fits the design of this component, however, it uses waypoints to scroll to a section when a link is clicked. I imagine this version will need to toggle content.

http://lonelyplanet.github.io/backpack-ui/?selectedKind=Sectional%20nav&selectedStory=Default&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

TabbedNav was built for travel news to toggle content. It doesn't share the same design, but it needs to. It shares a lot of the same markup and styles as SectionalNav.

http://lonelyplanet.github.io/backpack-ui/?selectedKind=Tabbed%20nav&selectedStory=Default&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

SectionalNav and TabbedNav need to be combined into one component. Styles and markup should not be duplicated. However, the logic for each of these needs to be abstracted. We need an onClick to scroll to content and an onClick to toggle content.

**Comment by thomasthesecond** [comment]
> double check with ux about how they were envisioning this would work to make sure we cover all bases

Double checked with Brad, they are tabs that will toggle the visibility of the corresponding content.
