### ISSUE TITLE
Obtain country from users at email signup

### ISSUE THREAD

**Issue by chrissysievers** [lonelyplanet/backpack-ui#222]
Marketing would like to obtain a country origin from users who sign up for our email newsletter to enable regionalized marketing communications. This needs to happen across:

1. Home
2. Video
3. Travel News (see existing TN issue [here](https://github.com/lonelyplanet/wp-travelnews-frontend/issues/190) re: Salesforce integration)

Product believes the better solve is to obtain the country programmatically rather than updating the form's UI but would like a dev's opinion. In the event we are unable to determine IP, or would like a fall-back for a user to make a selection, Andy has included the design here for reference.
![screen shot 2017-04-13 at 10 08 23 am](https://cloud.githubusercontent.com/assets/20303852/25049246/7c5ae2ea-2106-11e7-8b3d-44dd37c4b10f.png)

____________

**For Reference**

[Original ask from Marketing](https://trello.com/c/wvzZ5O63/2133-newsletter-sign-up-form-phase-2): 
_Add a required Country drop-down list field in the sign up form on the homepage and video hub. Ensure that LP_SUBSCRIBER list is being populated ‘True’ against the LP_Editorial_Newsletter field, indicating that the user has signed up to the newsletter._  

Rob has confirmed the new structure would look like this:

newsletter[First_Name]
newsletter[email]
newsletter[country]
newsletter[LP_Editorial_Newsletter]

All fields except EmailAddress will reflect the field names defined in Salesforce. Because there is no way to test if the data is getting properly submitted without accessing Salesforce application, please let me and Rob know when this is ready for testing.

**Comment by jcreamer898** [comment]
We already get a location via our Fastly headers, so it'd make sense to just pull that in easily.

**Comment by jcreamer898** [comment]
Honestly, I think this should happen in `github.com/lonelyplanet/gonzo` in the newsletter controller.

**Comment by jcreamer898** [comment]
There's no need for the country logic to live in the UI component.

**Comment by chrissysievers** [comment]
Hey..talking to @robuye about the salesforce integration with Travel News, and this particular issue came up. He mentioned pulling this into gonzo so it works globally? I'll let him chime in now.

**Comment by robuye** [comment]
Hey guise,

I have updated code in Gonzo. If `Country_Location` or `country` fields are not set I will try to get the data from Fastly headers. It's already live. We support both field names, but please prefer `Country_Location` over `country`.

I have tested it in Travel News signup form and my country was updated as expected.

I tried to test it in `/video` but the form is broken and it's impossible to submit, there are some JS errors on the site not related to Salesforce/newsletter at all.

I tested the signup form on Homepage and it worked as expected too.

That makes it done from my point of view, let me know if you need something more.

**Comment by chrissysievers** [comment]
This issue was moved to lonelyplanet/gonzo#327
