### ISSUE TITLE
ModalContentSocialAuth should be customizable

### ISSUE THREAD

**Issue by toddkazakov** [lonelyplanet/backpack-ui#267]
`ModalContentSocialAuth` should allow passing `login_uri`, `client_id`, `scope`, `redirect_uri` and `target_link_uri` as props to allow reuse by different clients. 

In addition, there should be a container for error messages - e.g. when the email field from the facebook response is empty (if the facebook email is not verified).

Displaying the LP logo should optional.

**Comment by chrissysievers** [comment]
Looks like this one will be shifting into the next sprint?

**Comment by chrissysievers** [comment]
@nickfranciosi can this be closed?
