### ISSUE TITLE
UI Bugs

### ISSUE THREAD

**Issue by jcreamer898** [lonelyplanet/backpack-ui#360]
### All browsers
* [x] Missing icons http://d.pr/i/tLA1GS

### IE11
* [x] Scroll bug http://d.pr/i/JPLvsG
* [x] Checkbox border http://d.pr/i/6uqBwZ

**Comment by thomasthesecond** [comment]
The scroll bug appears to be caused by the text not breaking to multiple lines, which I think is the issue.

**Comment by thomasthesecond** [comment]
The missing icons bug seems to be present in every app and I think has been documented before. I can try to dig up an old issue for reference.

**Comment by thomasthesecond** [comment]
Looking into the checkbox border issue
