### ISSUE TITLE
Create heading for user list

### ISSUE THREAD

**Issue by thomasthesecond** [lonelyplanet/backpack-ui#383]
![image](https://user-images.githubusercontent.com/1479563/28678230-70bfd854-72b5-11e7-8545-7f852b1c2499.png)

Sketch file: https://www.dropbox.com/work/Digital%20Product/user%20lists/bp?preview=lp_lists_aligned_bp.sketch

_image not to scale_

**Comment by shawncothran** [comment]
<img width="520" alt="screen shot 2017-08-01 at 4 32 37 pm" src="https://user-images.githubusercontent.com/14968386/28848071-33931e2a-76d7-11e7-9cb7-1ef5bcad7544.png">
Desktop Version
