### ISSUE TITLE
Create user list, items component

### ISSUE THREAD

**Issue by thomasthesecond** [lonelyplanet/backpack-ui#384]
Displays POIs within a list. Each item, or POI, has a name, categories (CategoryLabel component), description and price range (#382).

The list should be titled with the name of the place, e.g., "Madrid, Spain"

see updated image below

Sketch file: https://www.dropbox.com/work/Digital%20Product/user%20lists/bp?preview=lp_lists_aligned_bp.sketch

_image not to scale_

**Comment by shawncothran** [comment]
updated comp:
![image](https://user-images.githubusercontent.com/14968386/29045080-cce4482e-7b87-11e7-9aa9-32550ec9dd2e.png)

**Comment by shawncothran** [comment]
notice, there will not be a top choice indicator, and there will be only one category, listed as `{category} in {city}`

**Comment by shawncothran** [comment]
We are not launching V1 with notes active for users
