### ISSUE TITLE
Desktop Modals have too much space around visible heading

### ISSUE THREAD

**Issue by nickfranciosi** [lonelyplanet/backpack-ui#512]

**Comment by nickfranciosi** [comment]
<img width="411" alt="screen shot on 2017-10-02 at 10 10 49" src="https://user-images.githubusercontent.com/4378776/31084488-2717fb26-a75a-11e7-85db-614b13c522ce.png">

**Comment by thomasthesecond** [comment]
I think this has been resolved with #368
