### ISSUE TITLE
Images still getting wrong orientation in avatar uploader

### ISSUE THREAD

**Issue by jcreamer898** [lonelyplanet/backpack-ui#518]
#### Bug
Uploading a photo that is in Portrait mode is still setting the orientation incorrectly in the avatar uploader.

Example photo.
![img_7156](https://user-images.githubusercontent.com/472487/31409140-7bc17392-add0-11e7-9fab-4da113edfc90.JPG)

**Comment by jcreamer898** [comment]
lol, looks like even github has trouble with it... hahaha

**Comment by WunderBart** [comment]
Unless you're using some lib to do the orientation extraction & rotation, this might help to do it client-side: https://stackoverflow.com/questions/20600800/js-client-side-exif-orientation-rotate-and-mirror-jpeg-images/40867559#40867559 (there's a snippet for orientation extraction, too)

Self-advertising lvl 9000 :trollface:

**Comment by jcreamer898** [comment]
lolz

**Comment by laserchicken** [comment]
thanks @WunderBart very helpful; I pushed my [changes](https://github.com/lonelyplanet/backpack-ui/pull/558), there is still something wrong, images with orientation 6 looks stretched but it may be styling problem, I will investigate

**Comment by WunderBart** [comment]
No worries, @laserchicken. If you need specs for it [I already wrote some](https://github.com/lonelyplanet/community/blob/master/spec/javascripts/lib/images_attacher_spec.js#L170-L447). Should save you some time 👌

**Comment by laserchicken** [comment]
should be fixed now
