### ISSUE TITLE
Inconsistent "Email me a link to sign in" button behavior

### ISSUE THREAD

**Issue by WunderBart** [lonelyplanet/backpack-ui#572]
Enabled & disabled states doesn't seem to be working well.

The button:
- enables after writing just one letter (at first attempt only),
- doesn't enable when proper email has been inserted via autofill,
- doesn't disable when email has been cleared (select all -> delete)

Example:
![lp sign in with email inconsistent button](https://user-images.githubusercontent.com/1451471/33485520-e7f1aee8-d6a6-11e7-9cf2-e4a11cb78536.gif)

Tested on Chrome.

**Comment by laserchicken** [comment]
done
